[package]
name = "gpg-import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.1"
chrono = { version = "0.4.24", default-features = false, features = ["time", "clock", "std"] }
exitcode = "1.1.2"
nom = "7.1.3"
