[package]
authors = ["Purple Clay <purpleclaygh@gmail.com>"]
name = "gpg-import"
edition = "2021"
license = "MIT"
version = "0.1.0"

[dependencies]
base64 = "0.21.1"
chrono = { version = "0.4.24", default-features = false, features = ["std"] }
git2 = { version = "0.17.2", default-features = false }
nom = "7.1.3"
