name: ci
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.*"
  pull_request:
    branches:
      - main
    # paths:
    #   - "src/**"
    #   - "Cargo.*"

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-24.04
    name: rustfmt / stable
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Cargo Format
        run: nix develop -c cargo fmt --check

  clippy:
    runs-on: ubuntu-24.04
    name: clippy / stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Cargo Clippy
        run: nix develop -c cargo clippy -- -Dwarnings

  alejandra:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Run Alejandra
        run: nix develop -c alejandra --check .

  typos:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Run Typos
        run: nix develop -c typos

  test:
    runs-on: ${{ matrix.os }}
    name: test / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Run tests
        run: nix develop -c cargo test

  build:
    runs-on: ubuntu-24.04
    name: build / ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform:
          - name: linux_x86_64_musl
            target: x86_64-unknown-linux-musl
          - name: linux_aarch64_musl
            target: aarch64-unknown-linux-musl
          - name: darwin_x86_64
            target: x86_64-apple-darwin
          - name: darwin_aarch64
            target: aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: purpleclay
          authToken: "${{ secrets.GH_CACHIX }}"
          skipPush: true
          useDaemon: false

      - name: Build
        run: nix develop -c cargo zigbuild --locked --release --target ${{ matrix.platform.target }}
