name: nix-patch
on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write
jobs:
  nix-patch:
    runs-on: ubuntu-24.04
    steps:
      - name: Git Clone
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Install Nix
        uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Strip Tag Prefix
        id: strip_tag
        run: |
          TAG=${GITHUB_REF##*/}
          STRIPPED_TAG=${TAG#v}
          echo "tag=${STRIPPED_TAG}" >> $GITHUB_OUTPUT

      - name: Patch Version
        run: |
          sed -i 's/version = "[^"]*";/version = "${{ steps.strip_tag.outputs.tag }}";/' default.nix

      - name: Patch Hash
        run: |
          sed -i 's/hash =/# hash =/' default.nix
          set +e
          nix build .#default 2>&1 | tee error.log
          set -e
          HASH=$(grep -oP '(got|specified):\s+(sha256-\S+)' error.log | awk '{print $2}' | tail -1)
          if [ -z "$HASH" ]; then
            echo "Failed to extract hash from error log"
            cat error.log
            exit 1
          fi
          sed -i "s|# hash = \"[^\"]*\";|hash = \"$HASH\";|" default.nix

      - name: Patch CargoHash
        run: |
          set +e
          nix build .#default 2>&1 | tee error.log
          set -e
          HASH=$(grep -oP '(got|specified):\s+(sha256-\S+)' error.log | awk '{print $2}' | tail -1)
          if [ -z "$HASH" ]; then
            echo "Failed to extract cargoHash from error log"
            cat error.log
            exit 1
          fi
          sed -i "s|cargoHash = \"[^\"]*\";|cargoHash = \"$HASH\";|" default.nix

      - name: Verify Build
        run: |
          nix build .#default
          ./result/bin/gpg-import version

      - name: Commit Changes
        run: |
          git add default.nix
          git commit -S -m "chore(nix): bump version of gpg-import to ${{ steps.strip_tag.outputs.tag }} [skip ci]"
          git push
